import { useMemo } from "react";
import * as THREE from "three";

const FAMILY_COLOR = {
  s: "#4FC3F7", // cyan/blue family
  p: "#FF8A65", // vivid contrasting family
  d: "#BA68C8", // distinctive family
};

/** Renders a set of sample points as ONE THREE.Points object (a single
 * draw call regardless of point count) via a raw BufferGeometry --
 * never individual React/mesh objects per point, per the explicit
 * performance requirement. `points` is an array of {x,y,z} in atomic
 * units, already generated by orbitalSampling.js. */
export default function ProbabilityCloud({ points, family, size = 0.09, opacity = 0.8 }) {
  const geometry = useMemo(() => {
    const geo = new THREE.BufferGeometry();
    const positions = new Float32Array(points.length * 3);
    for (let i = 0; i < points.length; i++) {
      positions[i * 3] = points[i].x;
      positions[i * 3 + 1] = points[i].y;
      positions[i * 3 + 2] = points[i].z;
    }
    geo.setAttribute("position", new THREE.BufferAttribute(positions, 3));
    return geo;
  }, [points]);

  const color = FAMILY_COLOR[family] ?? FAMILY_COLOR.s;

  return (
    <points geometry={geometry}>
      <pointsMaterial color={color} size={size} sizeAttenuation transparent opacity={opacity} depthWrite={false} />
    </points>
  );
}

export { FAMILY_COLOR };
